build-HelloWorldFunction:
	cp *.py $(ARTIFACTS_DIR)
	cp requirements-requests.txt $(ARTIFACTS_DIR)
	python -m pip install -r requirements-requests.txt -t $(ARTIFACTS_DIR)
	rm -rf $(ARTIFACTS_DIR)/bin
